// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvybqttidwbtqdicsvzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2eWJxdHRpZHdidHFkaWNzdnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDI0NTEsImV4cCI6MjA2NzU3ODQ1MX0.jehV61rdRqB-0cGhmqcoXa8SsuPGYFyKmQmXikB9bxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});